Update build-app.yml

diff --git a/.github/workflows/build-app.yml b/.github/workflows/build-app.yml
--- a/.github/workflows/build-app.yml
+++ b/.github/workflows/build-app.yml
@@ -8,10 +8,13 @@ on:
 
 permissions:
   contents: read
+  
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    permissions:
+      checks: write
 
     steps:
     - uses: actions/checkout@v4
@@ -39,23 +42,17 @@ jobs:
         echo "GOOGLE_TIMEZONE_DEV=***" >> .env_dev
         echo "GOOGLE_CREDENTIALS_DEV=***" >> .env_dev
   
-    - name: Run tests and generate report
+    - name: Test with pytest
       run: |
-        pytest --junitxml=pytest_report.xml
-
-    - name: Upload test results
-      uses: actions/upload-artifact@v3
+        python3 -m pytest --verbose --junit-xml=junit.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: pytest-report
-        path: pytest_report.xml
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
 
-    - name: Display test results
-      if: always()
-      uses: dorny/test-reporter@v1
-      with:
-        name: Pytest
-        path: pytest_report.xml
-        reporter: junit
 
   deploy:
     runs-on: ubuntu-latest
